### ISSUE TITLE
FFZ and BTTV emote support

### ISSUE THREAD

**Issue by wolfrik17** [Enubia/ghost-chat#38]
It would be nice if FrankerFaceZ and BetterTwitchTV emotes were supported

**Comment by Akkuma** [comment]
Stale bot seems to be extraordinarily over aggressive. in two weeks the issue was closed.

**Comment by Enubia** [comment]
hey, yeah seems like, will reopen it

**Comment by Enubia** [comment]
Unfortunately I couldn't find a way yet to properly parse the FFZ emotes since the list required to fetch is to big.
And since I don't have the direct emote IDs I would need to fetch all of them at once which takes a lot of time.
BTTV is also not really possible atm since the BTTV guys don't provide any official docs for their api and they said that they don't intend to release it for public use. I will try to get it to work in the next few days but for now I will close this issue since there are no real solutions for those two right now. The base code however is implemented so that I don't forget about it.
