### ISSUE TITLE
Add a guide for getting started with the project: building it, preparing IDE, installing useful extensions, deploying it for the first time, debugging and testing

### ISSUE THREAD

**Issue by Juansero29** [Enubia/ghost-chat#390]
**Is your feature request related to a problem? Please describe.**
I just cloned the project. I have never worked with Vue, Electron nor Js. However I told myself that I would take some action on the Issues I opened by contributing. However I can't get to deploy the project once cloning the repo. There's no instructions whatsoever and the internet points me to documents on starting new projects, not deploying and testing existing ones. 

**Describe the solution you'd like**
Add to CONTRIBUTING.md how to deploy and test the project, with infomation on how to

- preparing the IDE (VS Code)
- installing useful extensions
- commands for building the project
- commands for deploying it for the first time
- how to debug it 
- how to test it

**Comment by Enubia** [comment]
I'm sorry that I can't find time to tackle all the open issues right now, I want to keep them open at least so that maybe other people who have time can create PRs for them. I removed stale bot since reopening issues all the time isn't really helpful at all. An update the CONTRIBUTING.md file with instructions on how to setup the environment for development will be coming today.

**Comment by Enubia** [comment]
CONTRIBUTING.md is update now with a setup section. @Juansero29

**Comment by Juansero29** [comment]
Thanks for that. I still don't see how to debug the project tho, is it automatically executed in debug mode?

**Comment by Enubia** [comment]
Vue code debugging is done in your browser, altough I honestly never used it and just console logged everything. You can open up the dev tools of the electron window with CTRL+SHIFT+I like you do it in chrome

**Comment by Juansero29** [comment]
Okay so I also needed to run `npm i @vue/cli-shared-utils`, found out by searching it on Google.
However I'm now getting a 
```
Syntax Error: Error: PostCSS plugin autoprefixer requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
```

I don't know how to solve it, can you give me any clues?

![image](https://user-images.githubusercontent.com/19156405/111368325-06122180-8696-11eb-8b48-222e9737dc96.png)

**Comment by Enubia** [comment]
this should be fixed with my last commit since I also ran into this issue, I installed the working versions of all packages, you might need to pull the master again

i also would recommend you delete your local package-lock.json and node_modules folder and try the installation again. maybe there are some conflicting packages still installed

**Comment by Juansero29** [comment]
Okay, running this commands in the following order, from the repo root folder, allowed me to finally start the app :) 

1. `npm install npm@latest -g`
2. `npm -v`
3. `git pull`
4. `rm -R .\node_modules\`
5. `npm install`
6. `npm start`

Hopefully this will help someone else too. Thanks for your advice which pointed me to the good direction @Enubia
