### ISSUE TITLE
Can't change options

### ISSUE THREAD

**Issue by Aevum11** [Enubia/ghost-chat#407]
I can't choose the save option or cancel at the bottom because the window is too large in settings and is not resizable. My resolution is 1920x1080. Windows 10. I have tried multiple programs to fix and nothing seems to work. I just want to clear the messages after 20 minutes :(

**Comment by Enubia** [comment]
can you post your config.json file by any chance?

it's located in 
```bash
%appdata%/Roaming/ghost-chat
```

**Comment by Aevum11** [comment]
It does not use all the screen space... It just goes beyond the bottom of the monitor and I can't click it but I can see save and cancel, just barely, if I drag it past the top of the screen. When I let go of it it just rubber bands back into place. I can post a video later on showing the exact issue if required. It only happens in settings as it is resizeable otherwise. The file is attached.
[config.zip](https://github.com/Enubia/ghost-chat/files/9854390/config.zip)

**Comment by Enubia** [comment]
What I can see is that the settings file looks normal.

I did already check the the settings window position stuff yesterday and tinkered around with it to remove the static position.
I'll probably relase a new version later on today so that the window is resizable again and can be moved. This should fix your specific problem.

What's causing this error is interesting tho, as i don't see anything that would force this behavior.

**Comment by Enubia** [comment]
@Aevum11 new release is published
please check if you still encounter this problem

https://github.com/Enubia/ghost-chat/releases/tag/v1.4.2
