### ISSUE TITLE
menu setting sometimes when right clicking on screen

### ISSUE THREAD

**Issue by archlord2k** [Enubia/ghost-chat#58]
**Checklist before reporting**
- Is it really a bug or actually a feature request?
- Is there already another issue related to your problem?
- Do you have resources to reproduce it?

**Describe the bug**
The setting menu shows on the middle of the screen as if you right click on the program while playing a game
and takes me out of the clickthrough
Not sure if it has anything to do with the game I play but i use shift right click MB a lot

**To Reproduce**

**Uncaught Exception Errors**
1. Navigate to ```%USERPROFILE%\AppData\Roaming\ghost-chat\logs
[main.log](https://github.com/Enubia/ghost-chat/files/4859494/main.log)

```
2. Attach the main.log file to the issue. (This contains the whole stack trace of the error message)

**Expected behavior**
I expected the setting menu from the program not to show and make my mouse active while playing

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

if you use discord 
you can contact me at archlord2k Kyl0#6352

**Comment by archlord2k** [comment]
![bug](https://user-images.githubusercontent.com/67706301/86277007-f7d1b300-bba3-11ea-97ab-a90f0b558401.png)
you can see the setting menu in the middle of the screen

**Comment by Enubia** [comment]
Hey, which version are you using? I checked the logs and noticed that there's an old error appearing which should've been fixed already afaik.

**Comment by archlord2k** [comment]
1.1.4.0

Ishmael cortez Sent from Outlook<http://aka.ms/weboutlook>
________________________________

**Comment by Enubia** [comment]
Sorry for not responding, had to do a lot of stuff lately. I will look into this before the next release since this behavior seems very odd and should not appear.

**Comment by Enubia** [comment]
so i've gone ahead and tested this and it seems like the problem is that you accidentally right click the chat while you are playing but do not release the right mouse button immediately which pulls the context menu to the middle of the screen or wherever you release the mouse button. Unfortunately I can't do anything about this but what I'd suggest you to do is set the window to clickthrough via the ghost icon. This prevents any interaction with the window unless you revert this via the tray icon menu.
